name: Documentation
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Pages
        uses: actions/configure-pages@v5

      - name: Checkout
        uses: actions/checkout@v5

      - name: Replace Google Profile Symlinks
        run: |
          cp -L docs/app-ads.txt docs/app-ads.txt.bak
          mv docs/app-ads.txt.bak docs/app-ads.txt

          cp -L docs/apps-ads.txt docs/apps-ads.txt.bak
          mv docs/apps-ads.txt.bak docs/apps-ads.txt

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Zensical
        run: pip install zensical

      - name: Build Static Site
        run: zensical build --clean

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

      - name: Deploy Page
        uses: actions/deploy-pages@v4
